### ISSUE TITLE
Error: Cannot find module '@actions/core'

### ISSUE THREAD

**Issue by ericknyoto** [Dovyski/payload-info-action#2]
```


Error: Cannot find module '@actions/core'
Require stack:
- /home/manobo/temp/actions-runner/_work/_actions/Dovyski/payload-info-action/v1/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/manobo/temp/actions-runner/_work/_actions/Dovyski/payload-info-action/v1/index.js:1:14)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/manobo/temp/actions-runner/_work/_actions/Dovyski/payload-info-action/v1/index.js'
  ]
}
```

**Comment by Dovyski** [comment]
This seems like an unsatisfied dependency. Have you run `npm install` at the root folder of the action?
